### ISSUE TITLE
update broke extension

### ISSUE THREAD

**Issue by andrewpak** [ogarcia/remove-rounded-corners#4]
after attempting to update this extension, I only get an error message. I tried uninstalling and reinstalling, still only getting error messages.

**Comment by ogarcia** [comment]
Please give me more info. What version of GNOME are you using? The extension version is 4 or 5? and What error message?

**Comment by andrewpak** [comment]
gnome 41.2  , I am using the extension ( I think the latest version? ) and I got a message to upgrade in firefox. When I went to upgrade it just says error. When I toggle the switch off and on, now it says it reinstalls but then I just get the same error message. Doesn't provide any more details when this occurs.

**Comment by ogarcia** [comment]
Mmm, it smell a problem with Firefox addon. Do following:

1. Disable extension in your Firefox Browser.
2. Go to https://extensions.gnome.org/extension/4201/remove-rounded-corners/ with Firefox addon disabled (or other browser).
3. Select latest version to download (sell version 41 -> extension version 5).
4. This must download a zip file `rrcogarcia.me.v5.shell-extension.zip`.
5. Create a folder `rrc@ogarcia.me` in your home in `~/.local/share/gnome-shell/extensions' (if exists delete ir before an recreate).
6. Copy zip file `rrcogarcia.me.v5.shell-extension.zip` in this new folder ``~/.local/share/gnome-shell/extensions/rrc@ogarcia.me'
7. Unzip it, it creates 3 files, `extension.js`, `metadata.json` and `stylesheet.css`. You can delete `rrcogarcia.me.v5.shell-extension.zip` if you want.
8. Restart your machine (very important because wayland don't reload extensions).
9. Open a shell and run `gnome-extensions enable rrc@ogarcia.me`
10. Tell me the results :wink:

**Comment by andrewpak** [comment]
Before I do this, I got a quick question. I have enabled other extensions in a similar way, but when I `ls ~/.local/share/gnome-shell/extensions` it doesn't appear that any of my extension are in that directory ( although the path does exist ). Do you know where my other installed extensions could possibly be? Some I had installed and enabled manually before using the browser plugin.

**Comment by ogarcia** [comment]
As [GNOME help says](https://help.gnome.org/admin/system-admin-guide/stable/extensions.html.en) only two locations are valid:
- ` ~/.local/share/gnome-shell/extensions/`: For user extensions
- `/usr/share/gnome-shell/extensions/`: For all users (wide-machine) extensions

You can do as help say. Press <kbd>Alt</kbd> + <kbd>F2</kbd> and write `lg` to open the looking glass and see enabled extensions and locate them.

**Comment by andrewpak** [comment]
Thanks, okay so after checking all my installed extensions are in the `/usr/share/gnome-shell/extensions`. Oddly enough, I just rebooted and logged in and your extension seems to be working. I double checked the Firefox plugin and I see your extension there and turned on now. If I encounter this error again, I will install it again manually. Thanks for your help!
